### ISSUE TITLE
struct User: optional fields isn't supported

### ISSUE THREAD

**Issue by denizzzka** [nexor/telega#19]
According to the bot API documentation (https://core.telegram.org/bots/api#user) some fields should be optional:

```d
struct User
{
    int    id;
    bool   is_bot;
    string first_name;
    string last_name; // Optional
    string username; // Optional
    string language_code; // Optional
}
```

But string null value in D represents empty string:
```d
assert(null == "");
```

**Comment by nexor** [comment]
Temporary blocked by https://github.com/libmir/asdf/issues/115, maybe it makes sense to find workaround.
